### ISSUE TITLE
upgrade core to 1.76.0

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat-bot/echo#20]
and deltachat-node / deltabot / simple bot version respectively

also mention used (core)-versions in readme's

- [ ] Python
- [x] c
- [x] rust
- [x] nodejs
- [x] mention used core versions in readme's

**Comment by missytake** [comment]
python bindings 1.77.1.dev64+g4c7c4e2a and simplebot 2.4.0 work with the current examples, deltabot 0.8.0 fails. Probably needs a new release or so

**Comment by Simon-Laux** [comment]
superseded by #30
