### ISSUE TITLE
nodejs_napi_jsonrpc: Echo bot won't respond after restart

### ISSUE THREAD

**Issue by realpixelcode** [deltachat-bot/echo#47]
`node .` works fine, but when stopping the process and restarting it, the echo bot won't respond anymore.

Work-around: Delete `deltachat-data` before restarting the bot.

**Comment by Simon-Laux** [comment]
probably needs an else block in the configure check that starts io (connect to mailserver) if already configured.

configure has startIo already included in the jsonrpc method:

https://github.com/deltachat/deltachat-core-rust/blob/749f00766fad79456f73498fe99c4160bce59a10/deltachat-jsonrpc/src/api/mod.rs#L301-L313

https://github.com/deltachat/deltachat-core-rust/blob/749f00766fad79456f73498fe99c4160bce59a10/deltachat-jsonrpc/typescript/generated/client.ts#L80
