### ISSUE TITLE
Use deltachat-node-bot-base for nodejs-bot

### ISSUE THREAD

**Issue by pabzm** [deltachat-bot/echo#7]
We've been working partly in parallel regarding NodeJS. I implemented a small abstraction layer for NodeJS to use as bot library: https://github.com/deltachat-bot/deltachat-node-bot-base

I suggest to use that library for the NodeJS-bot in order to avoid repetition. [The README](https://github.com/deltachat-bot/deltachat-node-bot-base/blob/master/README.md) includes example code that explains how to use it.

@Simon-Laux If you agree but don't want to do it yourself, let me know and I'll take it into my hands.

**Comment by Simon-Laux** [comment]
I would make a separate version that uses the abstraction layer.
Also I don't quite see the need for the bot base as long as it doesn't have convenience features like an easy way to register command..
Anyways I'd like to have both examples, also for python, one for each variant. The echo example here is cheap so why not have multiple of them?

**Comment by Simon-Laux** [comment]
Also your bot base is a bit oversimplified, I would aim for an api like discord.js has: https://discordjs.guide/command-handling/#individual-command-files

**Comment by pabzm** [comment]
I'm not interested in being lectured about what's cool, and what suits "professionals", so I'll rather close this.
